version: '3.8'

services:
  web:
    image: blandskron/portafolioweb:latest
    # Carga automática de todas tus variables (Email, Secret Key, etc.)
    env_file:
      - .env
    
    ports:
      - "8000:8000"
    
    environment:
      - DJANGO_DEBUG=${DJANGO_DEBUG:-False}
    
    volumes:
      # Persistencia de Base de Datos: Docker gestiona el archivo, no Windows.
      # Esto evita el error de montaje que tuviste.
      - sqlite_data:/app/blandskron
      # Persistencia de archivos estáticos para WhiteNoise
      - static_volume:/app/blandskron/staticfiles
    
    # Ruta absoluta al script que definimos en el Dockerfile
    command: /app/docker-entrypoint.sh
    restart: always

volumes:
  sqlite_data:
  static_volume: