version: '3.8'

services:
  web:
    image: blandskron/portafolioweb:tagname
    command: /app/docker-entrypoint.sh
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG:-false}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS:-0.0.0.0}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
    volumes:
      - static_volume:/app/staticfiles
      - ./db.sqlite3:/app/db.sqlite3

volumes:
  static_volume:
